### PR TITLE
[Docs] Update clerk and convex setup steps

### PR DESCRIPTION
**Pull request by superbahbi**

### CODE REVIEW

**Comment by ashuvssut** [comment]
@superbahbi Thanks for the PR.

I have updated the [convex and clerk setup steps](https://github.com/ashuvssut/cookied/pull/2/commits/cfb02393001eb20645c59d0d3a933be0ffd7e756)

If you get a chance to test them out, and if you find issues or if think something is missing, please open up another PR for those corrections.

**Comment by superbahbi** [comment]
It looks great. I was planning to open a new PR for the missing environment variable.

**Comment by ashuvssut** [comment]
> I was planning to open a new PR for the missing environment variable.

Ah, I appreciate your willingness to contribute! It's great to hear that you were planning to address the missing environment variables. I've actually made those changes myself in this PR. 

If you have any more ideas or if there are other areas you'd like to contribute to, feel free to open an issue beforehand. That way, we can avoid any potential overlap, and I can provide more context if needed. 

Thank you!

**Comment by superbahbi** [comment]
Will do. Also, can you label this as hacktoberfest-accepted?

**Comment by ashuvssut** [comment]
Certainly! Our repository already has the `hacktoberfest` label, so any merged PR will count as a valid contribution for Hacktoberfest.

The `hacktoberfest-accepted` label, however, is typically reserved for PRs that have valuable contribution efforts but couldn't be merged due to certain reasons. So rest assured, your contributions are indeed counted toward Hacktoberfest even without the specific `hacktoberfest-accepted` label.

Feel free to reach out, in case your PRs are not accepted as valid hacktoberfest PRs

**Pull request merged**
